version: '3.8'
services:
  curl-ubuntu:
    container_name: curl-ubuntu
    restart: always
    image: curl-ubuntu
    networks:
      vpcbr:
        ipv4_address: 10.6.0.5
    tty: true

  envoy-tproxy:
    container_name: envoy-tproxy
    image: envoy-tproxy
    build:
      context: .
      dockerfile: envoy.Dockerfile
      args:
        buildno:
    ports:
      - "4999"
      - "19000"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.6.0.6
    tty: true

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1